version: '3'

services:
  homecook_nginx:
    image: nginx:latest
    container_name: HomeCook-Nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - homecook_web
  homecook_db:
    image: postgres
    container_name: HomeCook-Postgres
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
  homecook_web:
    container_name: HomeCook-Django
    build:
      context: ../../
      dockerfile: Deployment/Development/Dockerfile
    command: bash -c "python manage.py migrate --noinput && gunicorn HomeCook.wsgi -b 0.0.0.0:8000"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      DEBUG: ${DEBUG}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
      STATIC_URL: ${STATIC_URL}
      AWS_DEFAULT_ACL: ${AWS_DEFAULT_ACL}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      CDN: ${CDN}
    expose:
        - "8000"
    depends_on:
      - homecook_db