# Generated by Django 2.2.1 on 2019-05-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Ingredients/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prepTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.IntegerField()),
                ('dishImage', models.ImageField(upload_to='Recipe/DishImages/')),
                ('bannerImage', models.ImageField(upload_to='Recipe/Banners/')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNumber', models.IntegerField()),
                ('instruction', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='StepInstructions/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, choices=[('ml', 'milliliters'), ('cups', 'cups'), ('liter', 'liters'), ('teaspoon', 'teaspoon'), ('tablespoon', 'tablespoon'), ('liter', 'liters'), ('oz', 'ounce'), ('gram', 'grams')], max_length=15)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Recipe.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Recipe.Recipe')),
            ],
        ),
    ]
