# Generated by Django 2.2.1 on 2019-05-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_auto_20190525_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'milliliters'), ('cups', 'cups'), ('liter', 'liters'), ('teaspoon', 'teaspoon'), ('tablespoon', 'tablespoon'), ('liter', 'liters'), ('oz', 'ounce'), ('gram', 'grams'), ('', '')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Recipe.Recipe'),
        ),
    ]
