# Generated by Django 2.2.1 on 2019-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_auto_20190526_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'milliliters'), ('cups', 'cups'), ('liter', 'liters'), ('teaspoon', 'teaspoon'), ('tablespoon', 'tablespoon'), ('liter', 'liters'), ('oz', 'ounce'), ('gram', 'grams'), ('', '')], default='', max_length=15),
        ),
    ]
