# Generated by Django 2.2.1 on 2019-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_auto_20190526_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'milliliters'), ('cups', 'cups'), ('teaspoon', 'teaspoon'), ('tablespoon', 'tablespoon'), ('l', 'liters'), ('oz', 'ounce'), ('g', 'grams'), (None, '')], default='', max_length=15, null=True),
        ),
    ]
