# Generated by Django 2.2.1 on 2019-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0007_auto_20190527_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'milliliters'), ('cups', 'cups'), ('tsp', 'teaspoon'), ('tb', 'tablespoon'), ('l', 'liters'), ('oz', 'ounce'), ('g', 'grams'), (' ', '')], default='', max_length=15),
        ),
    ]
